import json
import argparse

from time import time
from pathlib import Path

from rb.metrics import cmp
from utils import merge, get_definition

need_truth_tasks = ["cg/lv1", "cg/lv2", "cg/lv3", "exec/execute", "exec/testing", "fm/aef", "fm/anf"]

def get_compare_result(model_id: str, task: str, new: bool = False):
    update_file = True

    if new:
        compare_result = {}
        syntax_error = ""
        other_error = ""

    else:
        try:
            with open(saved_folder + "/ruled_metrics.json", encoding='utf-8') as f:
                compare_result = json.load(f)

            with open(saved_folder + "/ruled_syntax_error.txt", encoding='utf-8') as f:
                syntax_error = f.read()

            with open(saved_folder + "/ruled_other_error.txt", encoding='utf-8') as f:
                other_error = f.read()

            if len(compare_result) < len(run_samples):

                m = input(
                    f"{len(compare_result)} samples were compared. This run will proceed with the rest ('c' - continue, '<other>' - see the current result)? ")
                if m == "c":
                    pass
                else:
                    update_file = False
                    return compare_result, syntax_error, other_error, len(run_samples), syntax_error.count(
                        "-- SyntaxError"), update_file

            else:
                update_file = False
                return compare_result, syntax_error, other_error, len(run_samples), syntax_error.count(
                    "-- SyntaxError"), update_file

        except FileNotFoundError:
            compare_result = {}
            syntax_error = ""
            other_error = ""

    count_syntax_error = 0
    for k in run_samples:
        if k in compare_result:
            continue

        v = run_samples[k]

        if task in need_truth_tasks:

            if task.startswith("cg"):
                old_code = Path(OLD_CODE_FOLDER) / v["new_completion_path"]
            else:
                old_code = Path(OLD_CODE_FOLDER) / v["completion_path"]

            agent_output = Path(ANGENT_OUTPUTS_PATH) / task / model_id / v["new_completion_path"]

            old_src = old_code.read_text()
            new_src = agent_output.read_text()

            try:
                if task == "cg/lv1":
                    merged_src = merge(old_src, new_src, v["function_name"])
                    start = time()
                    result = cmp(old_src, merged_src, v["function_name"])
                    end = time()

                elif task == "fm/aef":
                    fn_moved_to = Path(ANGENT_OUTPUTS_PATH) / task / model_id / Path(
                        v["completion_path"]).parent / f"updated_{k}_{Path(v['need_update'][-1]).stem}.py"
                    
                    fn_def_after_move = get_definition(fn_moved_to.read_text(), v["function_name"])

                    if fn_def_after_move is None:
                        start = time()
                        result = cmp(old_src, new_src, v["function_name"])
                        end = time()

                    else:
                        unified_src_after_move = merge(new_src, fn_def_after_move, v["function_name"])
                        start = time()
                        result = cmp(old_src, unified_src_after_move, v["function_name"])
                        end = time()

                elif task == "fm/anf":
                    created_files_folder = Path(ANGENT_OUTPUTS_PATH) / task / model_id / Path(
                        v["completion_path"]).parent / f"created_files_{k}_anf"
                    current_src = ""
                    for file in sorted(created_files_folder.glob("*.py")):
                        current_src = merge(current_src, file.read_text(), v["function_name"])

                    src_after_extraction = Path(ANGENT_OUTPUTS_PATH) / task / model_id / v["new_completion_path"]
                    current_src = merge(current_src, src_after_extraction.read_text(), v["function_name"])

                    start = time()
                    result = cmp(old_src, current_src, v["function_name"])
                    end = time()

                else:
                    start = time()
                    result = cmp(old_src, new_src, v["function_name"])
                    end = time()

                print(f"Items `{k}` takes {end - start}s to compare")

                compare_result[k] = result

                all_keys = list(v.keys())
                for key in all_keys[5:]:
                    compare_result[k][key] = v[key]

            except SyntaxError as e:
                msg = f" -- SyntaxError with item `{k}`, code generated by LLM at {agent_output}\n     {e}"
                syntax_error += msg + "\n\n"
                count_syntax_error += 1
                print(e)

            except FileNotFoundError:
                all_keys = list(v.keys())
                compare_result[k] = {}
                for key in all_keys[5:]:
                    compare_result[k][key] = v[key]

            except Exception as e:
                msg = f" --       Error with item `{k}`, code generated by LLM at {agent_output}\n     {e}"
                other_error += msg + "\n\n"
                count_syntax_error += 1
                print(e)

        elif task in ["fm/delf", "fm/delif"]:
            all_keys = list(v.keys())
            compare_result[k] = {}
            for key in all_keys[2:]:
                compare_result[k][key] = v[key]

    return compare_result, syntax_error, other_error, len(run_samples), count_syntax_error, update_file


def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument("--model_id", type=str, required=True)
    #parser.add_argument("--truthdir", type=str, default="Source_Code_no_code")
    parser.add_argument("--outdir", type=str, required=True)
    parser.add_argument("--task", type=str, required=True)
    parser.add_argument("--new", action="store_true")
    parser.add_argument("--merge_judge", action="store_true")
    parser.add_argument("--unsave", action="store_true")

    return parser.parse_args()


if __name__ == "__main__":
    import pandas as pd
    import os

    args = parse_args()

    truthdir = "Source_Code_no_code" if args.task.startswith("cg") else "Source_Code"

    OLD_CODE_FOLDER = f"/home/xuanlong/Misbehaviors/misbehavior/DevEval/{truthdir}"
    ANGENT_OUTPUTS_PATH = f"/home/xuanlong/Misbehaviors/misbehavior/DevEval/{args.outdir}"
    saved_folder = f"/home/xuanlong/Misbehaviors/misbehavior/DevEval/{args.outdir}/{args.task}/{args.model_id}"

    with open(f"{ANGENT_OUTPUTS_PATH}/{args.task}/{args.model_id}/run_samples.json") as f:
        run_samples = json.load(f)

    os.makedirs(saved_folder, exist_ok=True)

    compare_result, syntax_error, other_error, \
        total_samples, count_syntax_error, update_file = get_compare_result(args.model_id, args.task, args.new)

    if update_file and not args.unsave:
        with open(saved_folder + "/ruled_metrics.json", 'w', encoding='utf-8') as f:
            json.dump(compare_result, f, indent=4)

        with open(saved_folder + "/ruled_syntax_error.txt", 'w', encoding='utf-8') as f:
            f.write(syntax_error)

        with open(saved_folder + "/ruled_other_error.txt", 'w', encoding='utf-8') as f:
            f.write(other_error)

    if args.merge_judge:
        with open(saved_folder + "/llm_judge_algo_result.json") as f:
            judge_algo = json.load(f)

        with open(saved_folder + "/llm_judge_IF_result.json") as f:
            judge_IF = json.load(f)

    df_rb = pd.DataFrame.from_dict(compare_result, orient="index")
    df_rb = df_rb.ne(0).astype(int)  # convert to 0/1

    if args.merge_judge:
        df_algo = pd.DataFrame({
            fname: {
                stat: 1 - result["true_or_false"]
                for stat, result in stats.items()
            }
            for fname, stats in judge_algo.items()
        }).T

        df_algo = df_algo.astype(int)
        df_algo = df_algo.rename(columns={
            "same_behavior": "algorithm",
            "same_time_complexity": "time_complexity"
        })

        df_if = pd.DataFrame.from_dict(judge_IF, orient="index")

        if "meets_spec" in df_if.columns:
            df_if = df_if[["meets_spec"]].astype(int)
        else:
            df_if = pd.DataFrame(columns=["meets_spec"])

        df_all = df_rb.join(df_algo, how="outer")
        df_all = df_all.join(df_if, how="outer")
        df_all = df_all.fillna(0).astype(int)

        total_samples = len(df_all) + count_syntax_error

        affected_counts = df_all.sum()

    else:
        total_samples = len(df_rb) + count_syntax_error
        affected_counts = df_rb.sum()

    affected_counts = pd.concat([
        pd.Series({"syntax_error": count_syntax_error}),
        affected_counts
    ])

    affected_counts = affected_counts.div(total_samples) * 100
    affected_counts = affected_counts.round(2)

    affected_counts = affected_counts.sort_values(ascending=False)
    affected_counts = affected_counts.reset_index()
    affected_counts.columns = ["category", "percentage"]

    print()
    print(f"\033[93m{args.model_id.upper()}:\033[0m")
    print(affected_counts)

    print(f"+ Task id: {args.model_id}/{args.task} (use `--task` to change the task id)")
    print(
        f"+ \033[93mCompare result saved at `{args.outdir}[/{args.task}/{args.model_id}]` (specify `--outdir` to change the path)\033[0m")

    if not args.new:
        print(
            f"+ \033[93mNote: The result you see is old. Use `--new` if you change the implementation of comparision\033[0m")

    print()

